### ISSUE TITLE
java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:

### ISSUE THREAD

**Issue by zhou13** [extrange/ibkr-docker#74]
If I run the docker for some time (or click a URL), I got the following error (in both stable and latest):

```
ibkr-1  | Tue Jan 16 14:58:58 2024
ibkr-1  |  Connections: accepted: 127.0.0.1::39138
ibkr-1  |  SConnection: Client needs protocol version 3.8
ibkr-1  |  SConnection: Client requests security type None(1)
ibkr-1  |  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
ibkr-1  | 172.22.0.1 - - [16/Jan/2024 14:58:58] code 404, message File not found
ibkr-1  |  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
ibkr-1  |  ComparingUpdateTracker: 0 pixels in / 0 pixels out
ibkr-1  |  ComparingUpdateTracker: (1:-nan ratio)
ibkr-1  | 2024-01-16 14:59:52:216 IBC: detected dialog entitled: Second Factor Authentication; event=Closed
ibkr-1  | 2024-01-16 15:00:22:216 IBC: detected dialog entitled: Second Factor Authentication; event=Closed
ibkr-1  | 2024-01-16 15:00:28:442 IBC: detected dialog entitled: Second Factor Authentication; event=Closed
ibkr-1  | 2024-01-16 15:00:30:467 IBC: detected dialog entitled: Downloading settings from server; event=Closed
ibkr-1  | LogModuleConfigurator-Init: Log4j Ver2.x found on classpath
ibkr-1  | LogModuleConfigurator-Init: LogModuleConfigurator initialized with Log4j Verd.x
ibkr-1  | 2024-01-16 15:00:42:374 IBC: detected frame entitled: ; event=Lost focus
ibkr-1  | 2024-01-16 15:00:42:374 IBC: detected frame entitled: ; event=Deactivated
ibkr-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
ibkr-1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
ibkr-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ibkr-1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
ibkr-1  | 	at java.util.Optional.ifPresent(Optional.java:159)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
ibkr-1  | 	at feature.webapp.E.b(E.java:766)
ibkr-1  | 	at feature.webapp.E.a(E.java:675)
ibkr-1  | 	at feature.webapp.E.c(E.java:638)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
ibkr-1  | 	... 7 more
ibkr-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
ibkr-1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
ibkr-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ibkr-1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
ibkr-1  | 	at java.util.Optional.ifPresent(Optional.java:159)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
ibkr-1  | 	at feature.webapp.E.b(E.java:766)
ibkr-1  | 	at feature.webapp.E.a(E.java:675)
ibkr-1  | 	at feature.webapp.E.c(E.java:638)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
ibkr-1  | 	... 7 more
ibkr-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
ibkr-1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
ibkr-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ibkr-1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
ibkr-1  | 	at java.util.Optional.ifPresent(Optional.java:159)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
ibkr-1  | 	at feature.webapp.E.b(E.java:766)
ibkr-1  | 	at feature.webapp.E.a(E.java:675)
ibkr-1  | 	at feature.webapp.E.c(E.java:638)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
ibkr-1  | 	... 7 more
ibkr-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
ibkr-1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
ibkr-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ibkr-1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
ibkr-1  | 	at java.util.Optional.ifPresent(Optional.java:159)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
ibkr-1  | 	at feature.webapp.E.b(E.java:766)
ibkr-1  | 	at feature.webapp.E.a(E.java:675)
ibkr-1  | 	at feature.webapp.E.c(E.java:638)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
ibkr-1  | 	... 7 more
ibkr-1  | 2024-01-16 15:00:44:323 IBC: detected frame entitled: Dow Jones Today's Top Ten; event=Activated
ibkr-1  | 2024-01-16 15:00:44:324 IBC: detected frame entitled: Dow Jones Today's Top Ten; event=Focused
ibkr-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
ibkr-1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
ibkr-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ibkr-1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
ibkr-1  | 	at java.util.Optional.ifPresent(Optional.java:159)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
ibkr-1  | 	at feature.webapp.E.b(E.java:766)
ibkr-1  | 	at feature.webapp.E.a(E.java:675)
ibkr-1  | 	at feature.webapp.E.c(E.java:638)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
ibkr-1  | 	... 7 more
ibkr-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
ibkr-1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
ibkr-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ibkr-1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
ibkr-1  | 	at java.util.Optional.ifPresent(Optional.java:159)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
ibkr-1  | 	at feature.webapp.E.b(E.java:766)
ibkr-1  | 	at feature.webapp.E.a(E.java:675)
ibkr-1  | 	at feature.webapp.E.c(E.java:638)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
ibkr-1  | 	... 7 more
ibkr-1  | 2024-01-16 15:00:45:618 IBC: detected dialog entitled: Pending Tasks; event=Closed
ibkr-1  | 2024-01-16 15:00:45:626 IBC: detected frame entitled: Dow Jones Today's Top Ten; event=Lost focus
ibkr-1  | 2024-01-16 15:00:45:627 IBC: detected frame entitled: Dow Jones Today's Top Ten; event=Deactivated
ibkr-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
ibkr-1  | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
ibkr-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ibkr-1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
ibkr-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ibkr-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
ibkr-1  | 	chromium => libasound.so.2 libnssutil3.so libnss3.so libgbm.so.1 libsmime3.so libnspr4.so
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
ibkr-1  | 	at java.util.Optional.ifPresent(Optional.java:159)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
ibkr-1  | 	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
ibkr-1  | 	at feature.webapp.E.b(E.java:766)
ibkr-1  | 	at feature.webapp.E.a(E.java:675)
ibkr-1  | 	at feature.webapp.E.c(E.java:638)
ibkr-1  | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
ibkr-1  | 	... 7 more
ibkr-1  | 2024-01-16 15:01:04:807 IBC: detected frame entitled: News & Research; event=Opened
ibkr-1  | 2024-01-16 15:01:04:851 IBC: detected frame entitled: News & Research; event=Activated
ibkr-1  | 2024-01-16 15:01:04:852 IBC: detected frame entitled: News & Research; event=Focused
ibkr-1  | Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: /opt/i4j_jres/Oda-jK0QgTEmVssfllLP/1.8.0_202/lib/amd64/libjfxmedia.so: libasound.so.2: cannot open shared object file: No such file or directory
ibkr-1  | 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
ibkr-1  | 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
ibkr-1  | 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
ibkr-1  | 	at java.lang.Runtime.load0(Runtime.java:809)
ibkr-1  | 	at java.lang.System.load(System.java:1086)
ibkr-1  | 	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
ibkr-1  | 	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
ibkr-1  | 	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
ibkr-1  | 	at com.sun.media.jfxmediaimpl.NativeMediaManager.lambda$new$33(NativeMediaManager.java:115)
ibkr-1  | 	at java.security.AccessController.doPrivileged(Native Method)
ibkr-1  | 	at com.sun.media.jfxmediaimpl.NativeMediaManager.<init>(NativeMediaManager.java:106)
ibkr-1  | 	at com.sun.media.jfxmediaimpl.NativeMediaManager$NativeMediaManagerInitializer.<clinit>(NativeMediaManager.java:77)
ibkr-1  | 	at com.sun.media.jfxmediaimpl.NativeMediaManager.getDefaultInstance(NativeMediaManager.java:89)
ibkr-1  | 	at com.sun.media.jfxmedia.MediaManager.getSupportedContentTypes(MediaManager.java:50)
ibkr-1  | 	at com.sun.javafx.webkit.prism.PrismGraphicsManager.getSupportedMediaTypes(PrismGraphicsManager.java:154)
ibkr-1  | 	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
ibkr-1  | 	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
ibkr-1  | 	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
ibkr-1  | 	at javafx.scene.web.WebEngine$PulseTimer.lambda$null$2(WebEngine.java:1228)
ibkr-1  | 	at com.sun.javafx.application.PlatformImpl.lambda$null$402(PlatformImpl.java:295)
ibkr-1  | 	at java.security.AccessController.doPrivileged(Native Method)
ibkr-1  | 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$403(PlatformImpl.java:294)
ibkr-1  | 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
ibkr-1  | 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
ibkr-1  | 	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$208(GtkApplication.java:245)
ibkr-1  | 	at java.lang.Thread.run(Thread.java:748)
ibkr-1  | #
ibkr-1  | # A fatal error has been detected by the Java Runtime Environment:
ibkr-1  | #
ibkr-1  | #  SIGSEGV (0xb) at pc=0x00007fd4ad6c35da, pid=45, tid=0x00007fd32c1906c0
ibkr-1  | #
ibkr-1  | # JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
ibkr-1  | # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode linux-amd64 compressed oops)
ibkr-1  | # Problematic frame:
ibkr-1  | # V  [libjvm.so+0x6c35da]  jni_GetArrayLength+0x3a
ibkr-1  | #
ibkr-1  | # Core dump written. Default location: /settings/core or core.45
ibkr-1  | #
ibkr-1  | # An error report file with more information is saved as:
ibkr-1  | # /settings/hs_err_pid45.log
ibkr-1  | #
ibkr-1  | # If you would like to submit a bug report, please visit:
ibkr-1  | #   http://bugreport.java.com/bugreport/crash.jsp
ibkr-1  | #
ibkr-1  | /opt/ibc/scripts/ibcstart.sh: line 504:    45 Aborted                 (core dumped) "$java_path/java" -cp "$ibc_classpath" $java_vm_options$autorestart_option $entry_point "$ibc_ini" "$ib_user_id" "$ib_password" ${mode}
ibkr-1  | IBC returned exit status 134
ibkr-1  | autorestart file not found
ibkr-1  |
ibkr-1  | TWS finished
ibkr-1  |
ibkr-1 exited with code 134
```

**Comment by Dave3991** [comment]
I solved by adding this
```
RUN apt update && apt install -y \
    libasound2 \
    libnss3 \
    libgbm1 \
    libnspr4
```

**Comment by zhou13** [comment]
Thank you. That fixes the problem for me.

**Comment by extrange** [comment]
Thanks @Dave3991. Added these to the dockerfile in the latest releases.
