### ISSUE TITLE
Can't connect to X11 window server using ':0' as the value of the DISPLAY variable

### ISSUE THREAD

**Issue by andrew521** [extrange/ibkr-docker#94]
edit: same error for ghcr.io/extrange/ibkr:latest
fresh compose with ghcr.io/extrange/ibkr:stable:

2024-04-09 07:51:52 Starting TWS with this command:
2024-04-09 07:50:27 2024/04/09 07:50:27 socat[11] N listening on AF=2 0.0.0.0:8888
2024-04-09 07:50:27 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2024-04-09 07:50:27 2024-04-09 07:50:27:718 IBC: An exception has occurred:
2024-04-09 07:50:27 java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
2024-04-09 07:50:27     at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
2024-04-09 07:50:27     at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
2024-04-09 07:50:27     at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
2024-04-09 07:50:27     at java.security.AccessController.doPrivileged(Native Method)
2024-04-09 07:50:27     at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
2024-04-09 07:50:27     at java.lang.Class.forName0(Native Method)
2024-04-09 07:50:27     at java.lang.Class.forName(Class.java:264)
2024-04-09 07:50:27     at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
2024-04-09 07:50:27     at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
2024-04-09 07:50:27     at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
2024-04-09 07:50:27     at java.lang.Class.forName0(Native Method)
2024-04-09 07:50:27     at java.lang.Class.forName(Class.java:264)
2024-04-09 07:50:27     at java.awt.Toolkit$2.run(Toolkit.java:860)
2024-04-09 07:50:27     at java.awt.Toolkit$2.run(Toolkit.java:855)
2024-04-09 07:50:27     at java.security.AccessController.doPrivileged(Native Method)
2024-04-09 07:50:27     at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
2024-04-09 07:50:27     at ibcalpha.ibc.IbcTws.createToolkitListener(Unknown Source)
2024-04-09 07:50:27     at ibcalpha.ibc.IbcTws.load(Unknown Source)
2024-04-09 07:50:27     at ibcalpha.ibc.IbcTws.main(Unknown Source)

**Comment by extrange** [comment]
Can you retry on the latest images? What is your `compose.yml`?
